version: '3.8'

services:
  # Backend Services (MCP Server, Main API, WhatsApp Server)
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: shopping_backend
    ports:
      - "8001:8001"  # MCP Server
      - "8000:8000"  # Main API
      - "5000:5000"  # WhatsApp Server
    environment:
      - MAIN_API_URL=http://backend:8000/api
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    networks:
      - shopping_network
    volumes:
      - ./backend:/app/backend
      - ./salesforce:/app/salesforce
      - ./.env:/app/.env
    restart: unless-stopped

  # Frontend
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: shopping_frontend
    ports:
      - "8080:8080"
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - shopping_network
    volumes:
      - ./frontend:/app
      - /app/node_modules
    restart: unless-stopped

  # Ngrok for WhatsApp webhook
  ngrok:
    image: ngrok/ngrok:latest
    container_name: shopping_ngrok
    command: http backend:5000
    ports:
      - "4040:4040"  # Ngrok web interface
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    depends_on:
      - backend
    networks:
      - shopping_network
    restart: unless-stopped

networks:
  shopping_network:
    driver: bridge